### PR TITLE
Dispose functions must free original c memory, not generated go memory

### LINKED ISSUE #108: tu.DisposeTokens() returns incorrect memory
I may have run into a problem with the v3.7 code.  Don't know if it is there in earlier branches because I went right to 3.7.

In trying to figure out how to parse BinaryOperator Cursors, I ran into a stackoverflow suggestion about tokenizing the cursor and iterating through the tokens to find the actual operator in question.  Kind of weird that libclang makes us do that, but okay.  (Maybe there is a more straightforward method that I haven't run into yet.)

And of course because there is an array that is allocated by libclang, it later has to be disposed.  But the tu.DisposeTokens() function causes a memory exception when I run it under a 'go test' environment, claiming the memory being returned to malloc didn't come from malloc, and in fact the DisposeTokens() code looks wrong.  It goes out of its way *not* to use the same array that had been used to underpin the slice in the first place by tu.Tokenize(), but that's the array that needs to be returned to the C heap. 

Here's a diff that seems to fix it for me.  

```diff
diff --git a/clang/translationunit_gen.go b/clang/translationunit_gen.go
index 8c3ea1b..6e4a93d 100644
--- a/clang/translationunit_gen.go
+++ b/clang/translationunit_gen.go
@@ -329,14 +329,8 @@ func (tu TranslationUnit) Tokenize(r SourceRange) []Token {
 
 // Free the given set of tokens.
 func (tu TranslationUnit) DisposeTokens(tokens []Token) {
-       ca_tokens := make([]C.CXToken, len(tokens))
-       var cp_tokens *C.CXToken
-       if len(tokens) > 0 {
-               cp_tokens = &ca_tokens[0]
-       }
-       for i := range tokens {
-               ca_tokens[i] = tokens[i].c
-       }
+       gos_tokens := (*reflect.SliceHeader)(unsafe.Pointer(&tokens))
+       cp_tokens := (*C.CXToken)(unsafe.Pointer(gos_tokens.Data))
 
        C.clang_disposeTokens(tu.c, cp_tokens, C.uint(len(tokens)))
 }
```

### PR DESCRIPTION
**Pull request by marxriedl**
Fixes #108

### CODE REVIEW

File: headerfile.go [hunk 1]
```diff
@@ -50,6 +50,8 @@ func (h *HeaderFile) addMethod(f *Function, fname string, fnamePrefix string, rt
 }
 
 func (h *HeaderFile) addBasicMethods(f *Function, fname string, fnamePrefix string, rt Receiver) bool {
+	//fmt.Printf("%s, %d\n", fname, len(f.Parameters))
```
Comment (zimmski) [inline headerfile.go]: Remove the debugging printf

File: ast.go [hunk 2]
```diff
@@ -145,7 +145,12 @@ func (fa *ASTFunc) generateParameters() []ast.Expr {
 		if p.Type.IsSlice && !p.Type.IsReturnArgument {
 			hasDeclaration = true
 
-			fa.addGoToCSliceConversion(p.Name, p.Type)
+			
+			if _, ok := p.Heuristics["pass_c"]; !ok {
```
Comment (zimmski) [inline ast.go]: You might kill me for this but I do not think that we should add a "Heuristics" map to any struct:
- Your intention for the maps was probably to make future similar changes easier but the future type interaction is very limited even later, but even then I think that it is easier and type-safer to add a flag.
- The only map that is currently used is of the FunctionParameter, so the other maps are not needed at all right now.
- Using keys makes it harder to safely use an API -> no compile errors

So I would be proposing to add a flag to the FunctionParameter struct BUT I am wondering. Shouldn't this be the default anyhow?

Comment (zimmski) [inline ast.go]: So I had a look at some functions of the Clang API and I think we can just use that as the default for arrays and slices. For example have a look at "clang_reparseTranslationUnit".

File: ast.go [hunk 3]
```diff
@@ -652,6 +657,37 @@ func (fa *ASTFunc) addCToGoSliceConversion(name string, cname string, lengthOfSl
 	})
 }
 
+func (fa *ASTFunc) addCArrayFromGoSlice(name string, cname string, typ Type) {
+	sliceType := getSliceType(typ)
+
+	fa.addAssignment("gos_"+name, &ast.CallExpr{
```
Comment (zimmski) [inline ast.go]: Should we maybe do this in just one generated line?

```go
cp_unsavedFiles := (*C.struct_CXUnsavedFile)(unsafe.Pointer((*reflect.SliceHeader)(unsafe.Pointer(&unsavedFiles)).Data))
```

The "gos_" variable is used used only once temporarily.

File: ast.go (hunk 2 above)
Comment (marxriedl) [inline ast.go]: I seriously have no clue whatsoever anymore what my intention with the Heuristics map was

Comment (marxriedl) [inline ast.go]: this will take a while...

Comment (marxriedl) [inline ast.go]: Ok, I'm beginning to understand. I can't reconstruct what I intended with the heuristics map - lets say I wanted to be future proof.
I'm not entirely sure about the default thing, this would mean that we actually handled all array/slice parameters wrong in the first place.

Comment (marxriedl) [inline ast.go]: Which would make sense; just want to be sure

Comment (marxriedl) [inline ast.go]: (would also make the fix quite small so I'm all for it)

Comment (zimmski) [inline ast.go]: We used a new array with the same elements. I looked through the code, most of the time it is wrong.

Comment (marxriedl) [inline ast.go]: Ok, but only most of the time. Could you give me an example where it was correct?

Comment (zimmski) [inline ast.go]: I think I have not found one that was correct with a copy, but "clang_sortCodeCompletionResults" is a case where both version work because we do not need the original array. So it is not wrong, that is what I meant.

Comment (marxriedl) [inline ast.go]: Well then, I will rework this in the afternoon.

File: ast.go (hunk 3 above)
Comment (marxriedl) [inline ast.go]: True, but I don't like long lines

File: headerfile.go [hunk 4]
```diff
@@ -69,7 +70,7 @@ func (h *HeaderFile) addBasicMethods(f *Function, fname string, fnamePrefix stri
 
 		return h.addMethod(f, fname, fnamePrefix, rt)
 	} else if len(f.Parameters) == 1 && h.IsEnumOrStruct(f.Parameters[0].Type.GoName) && strings.HasPrefix(fname, "dispose") && f.ReturnType.GoName == "void" {
-		fname = "Dispose"
+		fname = "Dispose"
```
Comment (zimmski) [inline headerfile.go]: Looks like gofmt was not applied to this file?

File: headerfile.go [hunk 5]
```diff
@@ -50,6 +50,7 @@ func (h *HeaderFile) addMethod(f *Function, fname string, fnamePrefix string, rt
 }
 
 func (h *HeaderFile) addBasicMethods(f *Function, fname string, fnamePrefix string, rt Receiver) bool {
+
```
Comment (zimmski) [inline headerfile.go]: Remove this empty line

File: ast.go [hunk 6]
```diff
@@ -652,6 +652,37 @@ func (fa *ASTFunc) addCToGoSliceConversion(name string, cname string, lengthOfSl
 	})
 }
 
+func (fa *ASTFunc) addCArrayFromGoSlice(name string, cname string, typ Type) {
```
Comment (zimmski) [inline ast.go]: "cname" is never used.

File: ast.go (hunk 3 above)
Comment (zimmski) [inline ast.go]: It is generated code either way.

done

**Comment by zimmski** [comment]
Done with the review.

**Comment by zimmski** [comment]
I stumbled upon a problem for this PR `TranslationUnitFromSourceFile(sourceFilename string, clangCommandLineArgs []string, unsavedFiles []UnsavedFile)`. The problem is that Go's string type needs special treatment. We need to convert string arrays/slices using the copying function. Or do you see another solution?

File: headerfile.go (hunk 5 above)
Comment (marxriedl) [inline headerfile.go]: done

File: headerfile.go (hunk 4 above)
Comment (marxriedl) [inline headerfile.go]: done

File: ast.go (hunk 6 above)
Comment (marxriedl) [inline ast.go]: good catch, done

**Comment by marxriedl** [comment]
Because strings in C arrays of char arrays?
Makes sense, any other type besides strings?
